skripta 27136_test.yml

diff --git a/.github/workflows/27136_test.yml b/.github/workflows/27136_test.yml
--- a/.github/workflows/27136_test.yml
+++ b/.github/workflows/27136_test.yml
@@ -5,17 +5,62 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
+  check-tests:
+    runs-on: ubuntu-latest
 
+    outputs:
+      tests-exist: ${{ steps.check-tests.outputs.tests-exist }}
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Check for test scripts
+        id: check-tests
+        run: |
+          if [ -f "test_vaja2.cpp" ]; then
+            echo "::set-output name=tests-exist::true"
+            echo "Test scripts exist."
+          else
+            echo "Test scripts do not exist." >&2
+            echo "::set-output name=tests-exist::false"
+            exit 1
+          fi
+
+      - name: Create error log file
+        if: failure()
+        run: echo "Test scripts are missing" > napaka.txt
+
+      - name: Upload error log
+        if: failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: error-log
+          path: napaka.txt
+
+  run-tests:
+    needs: check-tests
+    if: needs.check-tests.outputs.tests-exist == 'true'
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: configure
-      run: ./configure
-    - name: make
-      run: make
-    - name: make check
-      run: make check
-    - name: make distcheck
-      run: make distcheck
+      - uses: actions/checkout@v3
+      
+      - name: Download error log
+        uses: actions/download-artifact@v2
+        with:
+          name: error-log
+          path: .
+
+      - name: Check error log
+        run: |
+          if [ -f napaka.txt ]; then
+            cat napaka.txt
+            exit 1
+          fi
+
+      - name: Install build dependencies
+        run: sudo apt-get update && sudo apt-get install -y build-essential
+
+      - name: Compile and run tests
+        run: |
+          g++ -o test test_vaja2.cpp vaja2.cpp && ./test
