Update 27136_test.yml - artefakt fix

diff --git a/.github/workflows/27136_test.yml b/.github/workflows/27136_test.yml
--- a/.github/workflows/27136_test.yml
+++ b/.github/workflows/27136_test.yml
@@ -7,7 +7,6 @@ on:
 jobs:
   check-tests:
     runs-on: [self-hosted, linux, x64]
-
     outputs:
       tests-exist: ${{ steps.check-tests.outputs.tests-exist }}
 
@@ -17,17 +16,14 @@ jobs:
       - name: Check for test scripts
         id: check-tests
         run: |
-          if [ -f "test_vaja2.cpp" ]; then
-            echo "::set-output name=tests-exist::true"
-            echo "Test scripts exist."
-          else
-            echo "Test scripts do not exist." >&2
-            echo "::set-output name=tests-exist::false"
+          if [ ! -f "test_vaja2.cpp" ]; then
+            echo "Test scripts are missing" >&2
             echo "Test scripts are missing" > napaka.txt
           fi
+        shell: bash
 
       - name: Upload error log if tests are missing
-        if: failure()
+        if: always()
         uses: actions/upload-artifact@v2
         with:
           name: error-log
@@ -35,7 +31,6 @@ jobs:
 
   run-tests:
     needs: check-tests
-    if: needs.check-tests.outputs.tests-exist == 'true'
     runs-on: [self-hosted, linux, x64]
     strategy:
       matrix:
@@ -43,8 +38,22 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Download error log if present
+        uses: actions/download-artifact@v2
+        with:
+          name: error-log
+
+      - name: Check error log
+        run: |
+          if [ -f "napaka.txt" ]; then
+            echo "Error log found, stopping workflow."
+            cat napaka.txt
+            exit 1
+          fi
+        shell: bash
+
       - name: Install specific GCC version
-        run: sudo apt-get install -y g++-${{ matrix.gcc-version }}
+        run: sudo apt-get update && sudo apt-get install -y g++-${{ matrix.gcc-version }}
 
       - name: Compile with the specified GCC version
         run: |
@@ -53,3 +62,4 @@ jobs:
           gcc -v
           g++ -o test test_vaja2.cpp vaja2.cpp
           ./test
+        shell: bash
